name: 'Svn checkout'
description: 'Checkout svn repo'
inputs:
  temp-dir:
    description: 'Checkout directory of svn repo'
    required: false
    default: "asf-dist"
  repo-path:
    description: 'Path to the svn repo ex: airflow/providers/'
    required: true
  repo-url:
    description: 'URL of the svn repo ex: https://dist.apache.org/repos/dist/release/airflow/'
    required: true


runs:
  using: "composite"
  steps:
    - name: "Checkout svn repo ${{ inputs.repo-url }}"
      shell: bash
      env:
        repo_url: ${{ inputs.repo-url }}
      run: |
        echo "Checking out git repo at $repo_url"
        git clone $repo_url ./${{ inputs.temp-dir }}
        echo "git repo checked out"