name: 'Config parser'
description: 'Parse the publish config file'
inputs:
  publish-config:
    description: 'Path to the publish config file'
    required: true
    default: 'publish-config.yml'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: "Config parser"
      shell: bash
      id: config-parser
      env:
        PUBLISH_CONFIG_FILE: ${{ inputs.publish-config }}
        PUBLISH_CONFIG_SCHEMA: ${{ github.action_path }}/src/scripts/publish-config.schema.json
      run: |
        python3 -m pip install uv
        uv run $GITHUB_ACTION_PATH/src/scripts/config_parser.py