name: 'Gh publish'
description: 'Publishes artifacts to pypi'
inputs:
  publish-config:
    description: 'Path to the publish config file'
    required: true
    default: 'publish-config.yml'
  temp-dir:
    description: 'Temporary directory to checkout svn repo'
    required: false
    default: 'temp-svn-repo'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: "Config parser"
      id: config-parser
      env:
        PUBLISH_CONFIG: ${{ inputs.publish-config }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        mkdir -p ${{ inputs.temp-dir }}
        python3 -m pip install pyyaml
        python3 $GITHUB_ACTION_PATH/src/scripts/config_parser.py "${PUBLISH_CONFIG}"
      shell: bash

    - name: Checkout SVN
      env:
        repo_url: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.url }}
      run: |
        echo "Checking out SVN repo at $repo_url"
        svn co $repo_url
        echo "SVN repo checked out"
      shell: bash
      working-directory: "./${{ inputs.temp-dir }}"

    - name: SVN check
      if: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.svn-check.enabled }} == "true"
      env:
        FILE_EXTENSIONS: ${{ toJson(fromJSON(steps.config-parser.outputs.pub_config).packages.extensions) }}
        PATH: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.path }}
        NAME: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.svn-check.name }}
        VERSION_FORMAT: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.version_pattern }}
        SCRIPT: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.svn-check.script }}
      working-directory: ./${{ inputs.temp-dir }}/${{ fromJSON(steps.config-parser.outputs.pub_config).packages.path }}
      run: |
        echo "Verifying $NAME"
        python3 $SCRIPT
      shell: bash

    - name: Checksum check
      if: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.checksum-check.enabled }} == "true"
      env:
        NAME: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.checksum-check.name }}
        type: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.checksum-check.type }}
        SCRIPT: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.checksum-check.script }}
      working-directory: ./${{ inputs.temp-dir }}/${{ fromJSON(steps.config-parser.outputs.pub_config).packages.path }}
      run: |
        echo "Verifying $name"
        chmod +x $SCRIPT
        $SCRIPT "$type"
      shell: bash