name: 'Publish to PyPI'
description: 'Publishes artifacts to pypi'
inputs:
  publish-config:
    description: 'Path to the publish config file'
    required: true
    default: 'publish-config.yml'
  temp-dir:
    description: 'Temporary directory to checkout svn repo'
    required: false
    default: 'temp-svn-repo'
  mode:
    description: 'Mode to run the action'
    required: false
    default: 'verify'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: "Config parser"
      uses: gopidesupavan/gh-pub/read-config@main
      with:
        publish-config: ${{ inputs.publish-config }}