project:
  name: gh-pub
  description: 'Example project for publishing to PyPI'
publisher:
  name: providers
  url: 'https://dist.apache.org/repos/dist/release/airflow/'
  path: airflow/providers/
checks:
  svn:
    - id: extension
      description: 'Extension check'
      identifiers:
        - type: regex,
          pattern: '.*'

    - id: package_name
      description: 'Package name check'
      identifiers:
        - type: regex,
          pattern: 'apache-airflow-providers-(.*?)-python3-none-any.whl'

  checksum:
    - id: checksum
      description: 'SHA512 Check'
      algorithm: '512'

  signature:
    - id: signature
      description: 'Signature Check'
      method: gpg
      keys: 'https://dist.apache.org/repos/dist/release/airflow/KEYS'

  publish:
    - id: publish
      description: 'Publish to PyPI'
      exclude: ['.*\.asc', '.*\.sha512']