name: 'Publish to PyPI'
description: 'Publishes artifacts to pypi'
inputs:
  publish-config:
    description: 'Path to the publish config file'
    required: true
    default: 'publish-config.yml'
  temp-dir:
    description: 'Temporary directory to checkout svn repo'
    required: false
    default: 'temp-svn-repo'
  mode:
    description: 'Mode to run the action'
    required: false
    default: 'verify'

runs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: "Setup dir"
      shell: bash
      run: |
        mkdir -p ${{ inputs.temp-dir }}

    - name: "Config parser"
      id: config-parser
      uses: ././read-config
      with:
        publish-config: ${{ inputs.publish-config }}

    - name: Checkout SVN
      shell: bash
      env:
        repo_url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
      run: |
        echo "Checking out SVN repo at $repo_url"
        svn co $repo_url
        echo "SVN repo checked out"
      working-directory: "./${{ inputs.temp-dir }}"

    - name: "Svn check"
      id: "svn-check"
      uses: ././svn
      with:
        svn-config: ${{ steps.config-parser.outputs.checks-svn }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}