name: Example pypi publish
description: 'Publish to PyPI'

on:
  workflow_dispatch:
    inputs:
      release-config:
        description: 'Path to the publish config file'
        required: true
        default: 'release-config.yml'
      temp-dir:
        description: 'Temporary directory to checkout svn repo'
        required: false
        default: "asf-dist"
      mode:
        description: 'Mode to run the action'
        required: false
        default: 'VERIFY'

jobs:
  gh-action-pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: test
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Setup Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.11'

     - name: "Config parser"
       id: config-parser
       uses: ./read-config
       with:
        release-config: ${{ inputs.release-config }}

     - name: "Checkout svn ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}"
       id: "svn-checkout"
       uses: ./init
       with:
         temp-dir: ${{ inputs.temp-dir }}
         repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
         repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path)}}

     - name: "Publish to PyPI"
       id: "publish-to-pypi"
       uses: ./publish
       with:
        publish-config: ${{ steps.config-parser.outputs.checks-publish }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path)}}
        temp-dir: ${{ inputs.temp-dir }}
        mode: ${{ inputs.mode }}
        publisher-name: ${{ steps.config-parser.outputs.publisher-name }}

     - name: "Download release distributions for ${{ steps.config-parser.outputs.publisher-name }}"
       uses: actions/download-artifact@v4
       with:
         merge-multiple: true
         path: ./dist

     - name: "Verify release distributions for ${{ steps.config-parser.outputs.publisher-name }}"
       shell: bash
       run: |
         ls -lthr ./dist

     - name: "Publishing test release distributions to PyPI"
       uses: pypa/gh-action-pypi-publish@release/v1
       if: inputs.mode == 'RELEASE'
       with:
         packages-dir: "./dist"